# Application Name
spring.application.name=MyJourneyBlog

# Server Configuration
server.port = 8080

# PostgreSQL Configuration
# Connection details
spring.datasource.url=jdbc:postgresql://localhost:5432/MyJourneyBlog_DB
spring.datasource.username=postgres
spring.datasource.password=POstgrES!!Ni25nG40!!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# File Upload Configuration (for future image uploads)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT Configuration
jwt.secret=secret-key-here-change-in-production-minimum-256-bits
jwt.expiration=86400000

# GitHub API Configuration
github.api.url=https://api.github.com
github.api.token=github_token_here

# Logging
logging.level.com.devjourney=DEBUG
logging.level.org.springframework.security=DEBUG

#Excluding Spring Security Auto-Configuration for test
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration