name: CI/CD Pipeline

on:
  # Trigger the workflow on push to the main branch
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: BUILD CODE & PUSH IMAGE
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Docker Hub repo name
          tags: ${{ secrets.DOCKER_USERNAME }}/my-journey-blog:latest
          # This helps speed up future builds
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # JOB 2: DEPLOY TO SERVER
  deploy:
    needs: build-and-push # Wait for Job 1 to finish
    runs-on: ubuntu-latest
    steps:
      - name: Execute Deploy Script on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # This runs the script in deploy.sh file on the server
          script: ./deploy.sh